/* Learn Piano Keys - content generation.
   Emits assets/pieces.js for the app, and the page definitions for every
   song, chord and scale, computed rather than hand-written.               */

const fs = require('fs');
const path = require('path');
const { buildPiece } = require('../data/notation.js');
const PIECE_DEFS = require('../data/pieces.js');
const ROOT = path.join(__dirname, '..');

const PIECES = PIECE_DEFS.map(buildPiece);

/* ---- the runtime score data the practice room loads ---- */
function emitRuntime() {
  const slim = PIECES.map(p => ({
    id: p.id, title: p.title, composer: p.composer, origin: p.origin,
    level: p.level, levelName: p.levelName, meter: p.meter, barUnits: p.barUnits,
    bpm: p.bpm, keyName: p.keyName, pickup: p.pickup || 0,
    blurb: p.blurb, tip: p.tip, levels: p.levels,
    notes: p.notes.map(n => ({ m: n.m, s: n.s, d: n.d, h: n.h, lvl: n.lvl, ...(n.f ? { f: n.f } : {}) })),
    totalUnits: p.totalUnits, bars: p.bars
  }));
  fs.writeFileSync(path.join(ROOT, 'assets/pieces.js'),
    '/* Generated by tools/gen-content.js from data/pieces.js. Do not edit. */\n' +
    'const PIECES = ' + JSON.stringify(slim) + ';\n');
  return slim.length;
}

/* ---- chords and scales, computed from intervals ---- */

/* Proper spelling matters. F major is F G A Bb C D E, never A#. A seven note
   scale uses each letter once and in order, so the letter is decided by the
   degree and the accidental is whatever gets it to the right pitch. */
const LETTERS = ['C', 'D', 'E', 'F', 'G', 'A', 'B'];
const NATURAL = { C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11 };

function parseRoot(root) {
  const letter = root[0];
  const acc = root.length > 1 ? (root[1] === '#' ? 1 : -1) : 0;
  return { letter, acc, pc: (NATURAL[letter] + acc + 12) % 12 };
}

function accidentalText(n) {
  if (n === 0) return '';
  if (n === 1) return '#';
  if (n === -1) return 'b';
  if (n === 2) return '##';
  if (n === -2) return 'bb';
  return '';
}

/* Names a pitch class using a required letter, which is what gives correct
   spelling: same letter, whatever accidental is needed to reach the pitch. */
function spellOn(letter, pc) {
  let diff = pc - NATURAL[letter];
  while (diff > 6) diff -= 12;
  while (diff < -6) diff += 12;
  return letter + accidentalText(diff);
}

/* Steps through the letters for a scale of consecutive degrees. */
function spellScale(root, intervals, degreeSteps) {
  const r = parseRoot(root);
  const startIndex = LETTERS.indexOf(r.letter);
  return intervals.map((iv, i) => {
    const letter = LETTERS[(startIndex + degreeSteps[i]) % 7];
    return spellOn(letter, (r.pc + iv) % 12);
  });
}

const pretty = n => n.replace(/##/g, ' double sharp').replace(/bb/g, ' double flat')
                     .replace('#', ' sharp').replace(/b$/, ' flat');

const CHORD_PAGES = [
  ['C', 'major'], ['G', 'major'], ['D', 'major'], ['A', 'major'], ['E', 'major'], ['F', 'major'],
  ['A', 'minor'], ['E', 'minor'], ['D', 'minor'], ['B', 'minor'], ['C', 'minor'], ['G', 'minor']
];
const SCALE_PAGES = [
  ['C', 'major'], ['G', 'major'], ['D', 'major'], ['F', 'major'], ['A', 'major'], ['E', 'major'],
  ['A', 'natural minor'], ['E', 'natural minor'], ['D', 'natural minor'],
  ['A', 'harmonic minor'], ['C', 'major pentatonic'], ['A', 'minor pentatonic']
];

const CHORD_IV = { major: [0, 4, 7], minor: [0, 3, 7] };
const CHORD_DEG = [0, 2, 4];                       // root, third, fifth

const SCALE_IV = {
  major: [0, 2, 4, 5, 7, 9, 11, 12],
  'natural minor': [0, 2, 3, 5, 7, 8, 10, 12],
  'harmonic minor': [0, 2, 3, 5, 7, 8, 11, 12],
  'major pentatonic': [0, 2, 4, 7, 9, 12],
  'minor pentatonic': [0, 3, 5, 7, 10, 12]
};
const SCALE_DEG = {
  major: [0, 1, 2, 3, 4, 5, 6, 7],
  'natural minor': [0, 1, 2, 3, 4, 5, 6, 7],
  'harmonic minor': [0, 1, 2, 3, 4, 5, 6, 7],
  'major pentatonic': [0, 1, 2, 4, 5, 7],          // degrees 1 2 3 5 6 of the major
  'minor pentatonic': [0, 2, 3, 4, 6, 7]           // degrees 1 b3 4 5 b7 of the minor
};

const chordNotes = (root, type) => spellScale(root, CHORD_IV[type], CHORD_DEG);
const scaleNotes = (root, type) => spellScale(root, SCALE_IV[type], SCALE_DEG[type]);

/* Standard right-hand fingering for the scales we publish. Written out
   rather than computed, because real fingering is a physical decision. */
const SCALE_FINGERS = {
  'C major': '1 2 3 1 2 3 4 5', 'G major': '1 2 3 1 2 3 4 5', 'D major': '1 2 3 1 2 3 4 5',
  'F major': '1 2 3 4 1 2 3 4', 'A major': '1 2 3 1 2 3 4 5', 'E major': '1 2 3 1 2 3 4 5',
  'A natural minor': '1 2 3 1 2 3 4 5', 'E natural minor': '1 2 3 1 2 3 4 5',
  'D natural minor': '1 2 3 1 2 3 4 5', 'A harmonic minor': '1 2 3 1 2 3 4 5',
  'C major pentatonic': '1 2 3 1 2 3', 'A minor pentatonic': '1 2 3 1 2 3'
};

/* Descriptions have to earn a click and be genuinely unlike each other.
   The note letters alone are not enough, because C major and A major use
   the same seven letters, so each one leads with what makes it different. */
/* Key signatures are a real, checkable fact that differs for every scale,
   which is what keeps these descriptions genuinely distinct rather than
   template variations of each other. */
const KEY_SIG = {
  'C major': 'no sharps or flats', 'G major': 'one sharp', 'D major': 'two sharps',
  'A major': 'three sharps', 'E major': 'four sharps', 'F major': 'one flat',
  'A natural minor': 'no sharps or flats', 'E natural minor': 'one sharp',
  'D natural minor': 'one flat', 'A harmonic minor': 'a raised seventh',
  'C major pentatonic': 'five bright notes and no clashing intervals',
  'A minor pentatonic': 'five notes and the backbone of blues soloing'
};

/* Relative keys share every note, so their descriptions must say so rather
   than pretend to be different. That is the useful fact anyway. */
const RELATIVE = {
  'A natural minor': 'C major', 'E natural minor': 'G major', 'D natural minor': 'F major'
};

function scaleDesc(label, names, blacks, fing) {
  const notes = names.slice(0, -1).join(' ');
  if (RELATIVE[label]) {
    const shapes = {
      'A natural minor': `Same seven notes as ${RELATIVE[label]}, started from ${names[0]}: ${notes}. Fingering ${fing}, free to hear and play.`,
      'E natural minor': `${label}: ${notes}. It shares a key signature with ${RELATIVE[label]}, one sharp. Fingering ${fing}. Free.`,
      'D natural minor': `Notes of ${label}: ${notes}, with a B flat. Relative to ${RELATIVE[label]}. Fingering ${fing}, played free in your browser.`
    };
    return shapes[label];
  }
  const sig = KEY_SIG[label] || '';
  const accs = names.slice(0, -1).filter(n => n.length > 1);
  if (blacks === 0) return `${label} has ${sig}: ${notes}. Fingering ${fing} on a keyboard you can hear. Free to use.`;
  if (accs.length === 1) return `${label} has ${sig}, ${accs[0]}. Notes: ${notes}. Standard fingering ${fing}, played and heard free.`;
  return `Notes of ${label}: ${notes}. Key signature ${sig} (${accs.join(', ')}). Fingering ${fing}. Free to hear and play.`;
}

function chordDesc(label, names, type) {
  const feel = type === 'major' ? 'the bright, settled sound' : 'the sad-sounding one';
  const black = names.filter(n => n.length > 1);
  const tail = black.length ? `Black keys: ${black.join(' and ')}.` : 'All white keys.';
  return `${label} is ${names.join(', ')}, ${feel}. ${tail} See it and hear it free.`;
}

function chordPages() {
  return CHORD_PAGES.map(([root, type]) => {
    const ivs = CHORD_IV[type];
    const names = chordNotes(root, type);
    const label = `${root} ${type}`;
    const shape = type === 'major' ? 'four semitones then three' : 'three semitones then four';
    return {
      slug: `${root.replace('#', '-sharp').toLowerCase()}-${type}-chord-piano`,
      kind: 'chord', root, type, names, ivs,
      title: `${label} chord on piano: notes and fingering`,
      desc: chordDesc(label, names, type).slice(0, 150),
      h1: `${label} chord on piano`,
      answer: `The ${label} chord is made of three notes: ${names.join(', ')}. Counting up from the root, that is ${shape}. ` +
              `Play it with your right thumb on ${names[0]}, middle finger on ${names[1]} and little finger on ${names[2]}. ` +
              `The same shape gives you any ${type} chord from any starting note.`,
      keyword: `${label.toLowerCase()} chord piano`
    };
  });
}

function scalePages() {
  return SCALE_PAGES.map(([root, type]) => {
    const ivs = SCALE_IV[type];
    const names = scaleNotes(root, type);
    const label = `${root} ${type}`;
    const blacks = names.slice(0, -1).filter(n => n.length > 1).length;
    const fing = SCALE_FINGERS[label] || '1 2 3 1 2 3 4 5';
    return {
      slug: `${root.replace('#', '-sharp').toLowerCase()}-${type.replace(/\s+/g, '-')}-scale-piano`,
      kind: 'scale', root, type, names, ivs, fingering: fing,
      title: `${label} scale on piano: notes and fingering`,
      desc: scaleDesc(label, names, blacks, fing).slice(0, 150),
      h1: `${label} scale on piano`,
      answer: `The ${label} scale is ${names.slice(0, -1).join(', ')}, returning to ${names[0]}. ` +
              (blacks === 0 ? 'It uses only white keys, which is why it is one of the first scales most people learn. '
                            : `It uses ${blacks} black ${blacks === 1 ? 'key' : 'keys'}. `) +
              `The usual right-hand fingering is ${fing}, tucking the thumb under after the third note.`,
      keyword: `${label.toLowerCase()} scale piano`
    };
  });
}

function songPages() {
  return PIECES.map(p => ({
    slug: `${p.id}-piano-notes`,
    kind: 'song', piece: p,
    title: `${p.title} piano notes for beginners`.slice(0, 60),
    desc: (`${p.title} piano notes, free. ${p.blurb}`).slice(0, 149),
    h1: `${p.title}: piano notes for beginners`,
    answer: `${p.title} is in ${p.keyName} and runs to ${p.bars} bars. ${p.blurb} ` +
            `There are three levels here: the melody on its own, the melody with one bass note per bar, and both hands together. ` +
            `Every note shows the finger to use, and the music waits for you rather than running ahead.`,
    keyword: `${p.title.toLowerCase()} piano notes`
  }));
}

module.exports = { PIECES, emitRuntime, chordPages, scalePages, songPages };

if (require.main === module) {
  const n = emitRuntime();
  console.log(`emitted ${n} pieces to assets/pieces.js`);
  console.log(`${chordPages().length} chord pages, ${scalePages().length} scale pages, ${songPages().length} song pages`);
}
